[build]
builder = "nixpacks"
buildCommand = "npm install && node ace build"

[deploy]
startCommand = "cd build && npm ci --omit=dev && node bin/workers.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
